FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
openjdk-11-jre \
&& rm -rf /var/lib/apt/lists/*

COPY calc.jar /appcalc/calc.jar

WORKDIR /appcalc

ENV DISPLAY=host.docker.internal:0

CMD ["java", "-jar", "calc.jar"]